### ISSUE TITLE
ERDAS 2018 CRACK INSTALLATION

### ISSUE THREAD

**Issue by sabyasachi1992** [geopandas/scipy2018-geospatial-data#26]
I am searching ERDAS 2018 crack because of its numerical spatial model application which is not supporting previous version of ERDAS. Kindly someone please suggest me how to use new erdas 2018 crack version

**Comment by ljwolf** [comment]
Hi,

Not sure why this is where you think you'll find that, but software piracy is definitely not the point of this repository.
